#!/usr/bin/env node
/**
 * patch-once.mjs - one-time surgery, 2026-09-16.
 *
 * Removes the hidden sr-only "body SEO" blocks from index, proof and expect,
 * and drops a visible questions section into index.html in their place.
 *
 * WHY: the site kit hard-bans hidden or offscreen text written for crawlers.
 * It drifts from the visible page within weeks, and then every machine
 * describes a business we do not run. The index block also shipped a SECOND
 * H1 on the page, which muddies the outline a machine builds from it.
 *
 * Safe to run twice: every step is a no-op once applied.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const rd = (f) => fs.readFileSync(path.join(ROOT, f), "utf8");
const wr = (f, s) => fs.writeFileSync(path.join(ROOT, f), s, "utf8");
const log = [];

const HIDDEN = /\n  <!-- Hidden body SEO content[\s\S]*?<\/aside>\n/;

for (const f of ["index.html", "proof.html", "expect.html"]) {
  let html = rd(f);
  if (HIDDEN.test(html)) {
    html = html.replace(HIDDEN, "\n");
    wr(f, html);
    log.push(`${f}: removed hidden sr-only SEO block`);
  }
}

/* .sr-only stays in the stylesheet for genuine accessibility use, but nothing
   on the site uses it for crawler-only copy any more. */

/* --- index.html: visible questions section, generated by build.mjs --- */
{
  let html = rd("index.html");
  if (!html.includes("<!-- faq:start -->")) {
    const anchor = `    <!-- CLOSING CTA (dark) -->`;
    if (!html.includes(anchor)) throw new Error("index.html: closing CTA anchor not found");
    html = html.replace(
      anchor,
      `    <!-- 06 · QUESTIONS (visible, extractable. Generated from data/pages.mjs
         by scripts/build.mjs so the FAQPage schema and the page can never
         disagree. Edit the answers there, not here.) -->
    <!-- faq:start -->
    <!-- faq:end -->

${anchor}`
    );
    wr("index.html", html);
    log.push("index.html: inserted faq markers before the closing CTA");
  }

  /* the closing CTA was 06, the questions section now is */
  html = rd("index.html");
  if (html.includes(`<span class="eyebrow fade-item">06 / Contact</span>`)) {
    html = html.replace(
      `<span class="eyebrow fade-item">06 / Contact</span>`,
      `<span class="eyebrow fade-item">07 / Contact</span>`
    );
    wr("index.html", html);
    log.push("index.html: renumbered contact 06 to 07");
  }
}

/* --- every page: nav gets the Industries link, footer gets it too --- */
for (const f of ["index.html", "proof.html", "expect.html"]) {
  let html = rd(f);
  let changed = false;

  if (!/nav-link[^"]*" href="(\.\/)?for"/.test(html) && !html.includes(`href="for.html"`)) {
    html = html.replace(
      /(<a class="nav-link" href="proof\.html">Proof<\/a>)/,
      `$1\n        <a class="nav-link" href="for.html">Industries</a>`
    );
    changed = true;
  }
  if (!/<a href="for\.html">Industries<\/a>/.test(html) && html.includes(`<a href="proof.html">Proof</a>`)) {
    html = html.replace(
      /(<a href="proof\.html">Proof<\/a>)/,
      `$1\n          <a href="for.html">Industries</a>`
    );
    changed = true;
  }
  if (changed) { wr(f, html); log.push(`${f}: added Industries to nav and footer`); }
}

/* --- footer town line on the hand-authored pages --- */
for (const f of ["index.html", "proof.html", "expect.html"]) {
  let html = rd(f);
  if (!html.includes("footer-towns") && html.includes(`<div class="footer-legal">`)) {
    html = html.replace(
      `      <div class="footer-legal">`,
      `      <p class="footer-towns">Working with local businesses in Huntsville, Madison, Athens, Decatur, Meridianville, Harvest, Hazel Green, Owens Cross Roads, New Market, Gurley, and remotely across the United States.</p>
      <div class="footer-legal">`
    );
    wr(f, html);
    log.push(`${f}: added the served-towns footer line`);
  }
}

console.log(log.length ? log.map((l) => "  " + l).join("\n") : "  nothing to do, already patched");
